version: '3.8'

services:
  app:
    build: .
    image: mg-recipe-app
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/Recipe?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=0000
    command: tail -f /dev/null

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=Recipe
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0000
      - MYSQL_ROOT_PASSWORD=0000
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db-data: