version: '3.8'
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: Recipe
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/csv_files --init-file=/csv_files/init.sql --local-infile=1 --loose-local-infile=1
    volumes:
      - db_data:/var/lib/mysql
      - ./data:/csv_files
    networks:
      - my-network
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Recipe?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1111
    depends_on:
      - db
    networks:
      - my-network
    command: ["java", "-jar", "app.jar"]
    volumes:
      - image_data:/app/img_files
volumes:
  db_data:
  image_data:
networks:
  my-network:
    driver: bridge